<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<?php
	$conf = &ivPool::get('conf');
	$siteTitle = $conf->get('/config/imagevue/settings/sitetitle');
?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
		<title>控制面板 | <?php echo $siteTitle; ?></title>
		<link href="admin/css/admin_stylesheet.css" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<div  class="header">
			<h1>
				<a href="index.php">控制面板</a> | <a href="../"><?php echo $siteTitle; ?></a>
			</h1>
		</div>     
		<div class="infobar">
			<?php foreach (ivMessenger::get('notice') as $notice): ?>
				<div class="notice"><?php echo $notice; ?></div>
			<?php endforeach; ?> 
			<?php if ($this->defaultUser): ?>
				<div class="error">请使用 admin/admin 帐户登录，并且及时修改初始密码！</div>
			<?php endif; ?>
			<?php if ($this->defaultGuest): ?>
				<div class="notice">游客请使用 guest/guest 帐户登录！</div>
			<?php endif; ?>
			<?php if ($this->wrongPassword): ?>
				<div class="error">错误的登录名或密码！</div>
			<?php endif; ?>
		</div>
		<div id="content">
			<div id="user">
			<?php if ($this->defaultUser): ?>
				<form method="post" action="index.php?redirect=<?php echo urlencode('index.php?c=user'); ?>">
			<?php else: ?>
				<form method="post" action="">
			<?php endif; ?>
					<table class="usertable" border="0" cellspacing="0" cellpadding="0">
						<tr><td colspan="2" class="text captions">登录</td></tr>
						<tr>
							<td class="text right">用户名</td>
							<td class="text">
								<input name="login" type="text" class="mytext" id="textfield" />
							</td>
						</tr>
						<tr class="odd">
							<td class="text right">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</td>
							<td class="text">
								<input type="password" name="password" id="textfield2" class="mytext" />
							</td>
						</tr>
						<tr>
							<td colspan="2" class="text">
								<label>
									<input type="checkbox" name="rememberme" id="checkbox" />
									保持登录状态
								</label>
							</td>
						</tr>
						<tr>
							<td colspan="2" class="captions">
								<input type="submit" class="mysubmit" value="登录" style="padding: 2px 4px 2px 4px; margin: 5px 10px 5px 10px; float: right;" />
							</td>
						</tr>
					</table>
				</form>
			</div>
		</div>
	</body>
</html>